# Edit with extreme care.
#
# Shared provisioning helpers sourced by train/<Model> and by the retrain
# scripts that `semsage retrain` generates. Paths are relative to the install
# root (semsage runs these with the root as the working directory):
#
#     dece/<name>/<name>.dece   compiled model store
#     train/<name>.rc           bloom/label rc for that store
#     train/<name>.lua          per-phrase provisioner
#
# The bare model name (e.g. Aldous_1-2) is baked into the alias below. The
# train/<Model> scripts set $ALDOUS before sourcing this file; the retrain
# scripts generated by `semsage retrain` still pass it positionally as $1, so
# fall back to $1 when ALDOUS is unset.
: "${ALDOUS:=${1}}"

alias splinterpctl="splinterpctl --use dece/${ALDOUS}/${ALDOUS}.dece --rc-file train/${ALDOUS}.rc"

DIE() {
    echo "$@"
    exit 1
}

# Splinter must be installed before any helper below can run. Check the two
# binaries we depend on up front, at source time, so a missing install is a
# clear instruction rather than a confusing "command not found" mid-training.
for __bin in splinterpctl splinferencep; do
    command -v "$__bin" >/dev/null 2>&1 || \
        DIE "$__bin not found on PATH. Splinter is not installed -- run util/install_splinter first."
done
unset __bin

INIT() {
    __arg_error="INIT requires 3 arguments: store, slots, max_slot_len"
    [ -z "$1" ] && {
        die "$__arg_error"
    }
    [ -z "$2" ] && {
        die "$__arg_error"
    }
    [ -z "$3" ] && {
        die "$__arg_error"
    }
    # avoid invoking the alias
    /usr/local/bin/splinterpctl init "$1" --slots "$2" --length "$3" || die "Failed to initialize model"
}

SET() {
    splinterpctl set "$1" "$2"
}

UNSET() {
    splinterpctl unset "$1"
}

LABEL() {
    splinterpctl label "$1" "$2"
}

TYPE() {
    splinterpctl type "$1" "$2"
}

BIND() {
    splinterpctl bind "$1" "$2"
}

# for splinference communication while training
MKIPC() {
    # data ready
    SET "__lane_dr_1" "0"
    LABEL "__lane_dr_1" "signal-data-ready"
    BIND "signal-data-ready" 1

    # data waiting
    SET "__lane_dw_2" "0"
    LABEL "__lane_dw_2" "signal-data-waiting"
    BIND "signal-data-waiting" 2
}

RMIPC() {
    UNSET "__lane_dr_1"
    UNSET "__lane_dw_2"
}

# setup the IPC slots and start nomic
#
# START_EMBEDDER <store_path>
START_EMBEDDER() {
    __store="$1"
    [ -z "$__store" ] && DIE "START_EMBEDDER requires a store path"
    : "${EMBED_MODEL:=${MODEL_PATH:-gguf/nomic.gguf}}"
    MKIPC

    # Doorbell. The per-phrase lua labels its temp slots with bloom bit 0x1
    # (ev-attractor in the training bloom set, we just borrow the tag) and
    # bumps them to wake the butler.
    #
    # A bump only pulses the signal group its label is BOUND to -- so bind
    # label 0x1 we bind its current occupant, which is 'ev-attractor' in Aldous_1-0.rc
    # to group 0, the group the butler watches, up front.
    #
    # This doesn't alter anything that remains once the model is trained.
    BIND "ev-attractor" 0

    __EMBEDDER_LOG=$(mktemp "${TMPDIR:-/tmp}/splinference.XXXXXX")
    # --vector-training makes embeddings write-once (only zeroed slots are
    # filled), so re-pulses never clobber a centroid the lua already wrote.
    splinferencep "$__store" "$EMBED_MODEL" 0 --vector-training > "$__EMBEDDER_LOG" 2>&1 &
    __EMBEDDER_PID=$!

    # Wait for the model to load and the daemon to reach its pulse loop before
    # we start depositing phrases, so the first bumps aren't dropped on the floor.
    __waited=0
    while :; do
        if ! kill -0 "$__EMBEDDER_PID" 2>/dev/null; then
            cat "$__EMBEDDER_LOG" >&2
            DIE "splinference exited during startup"
        fi
        grep -qiE "Active|next pulse|need embedding" "$__EMBEDDER_LOG" && break
        [ "$__waited" -ge 180 ] && DIE "splinference did not become ready in time"
        sleep 1
        __waited=$((__waited + 1))
    done
    echo "Embedder ready (pid ${__EMBEDDER_PID}, store ${__store}, model ${EMBED_MODEL})"
}

STOP_EMBEDDER() {
    if [ -n "$__EMBEDDER_PID" ] && kill -0 "$__EMBEDDER_PID" 2>/dev/null; then
        kill "$__EMBEDDER_PID" 2>/dev/null
        __waited=0
        while kill -0 "$__EMBEDDER_PID" 2>/dev/null; do
            [ "$__waited" -ge 10 ] && { kill -9 "$__EMBEDDER_PID" 2>/dev/null; break; }
            sleep 1
            __waited=$((__waited + 1))
        done
    fi
    [ -n "$__EMBEDDER_LOG" ] && rm -f "$__EMBEDDER_LOG"
    RMIPC
    unset __EMBEDDER_PID __EMBEDDER_LOG __store __waited
}

SENSOR() {
    # Create the tandem
    SET "$1" "-"
    splinterpctl orders set "${1}" 2
    SET "${1}" "${2}"
    SET "${1}.1" "variance_state"
    # Set up the structure
    LABEL "${1}" "${3}"
    LABEL "${1}.1" "${3}"
    TYPE "${1}" "vartext"
    TYPE "${1}.1" "vartext"
    # Now lua can just fill those in?
    splinterpctl lua train/${ALDOUS}.lua "${1}" "${2}" "$3"
}

INTRINSIC_SHUNT() {
    # Create the tandem
    SET "$1" "-"
    splinterpctl orders set "${1}" 2
    SET "${1}" "${2}"
    SET "${1}.1" "shunt_variance_state"
    # Set up the structure
    LABEL "${1}" "intrinsic-shunt"
    LABEL "${1}.1" "intrinsic-shunt"
    TYPE "${1}" "vartext"
    TYPE "${1}.1" "vartext"
    # Now lua can just fill those in?
    splinterpctl lua train/${ALDOUS}.lua "${1}" "${2}" "intrinsic-shunt"
    LABEL "${1}" "intrinsic-shunt"
}

MONOLITHIC_SHUNT() {
    SET "${1}" "${2}"
    TYPE "${1}" vartext
    LABEL "${1}" "shunt-attractor"
}

POST_TRAIN_MONOLITHIC_SHUNTS() {
    echo "Backfilling monolithic mean-pooling shunts ..."
    splinferencep --backfill-text-keys --vector-training "dece/${ALDOUS}/${ALDOUS}.dece" gguf/nomic.gguf 0 --oneshot
    # Vartext keys with labels bound to signal group 0 will automatically
    # have their vectors updated by splinference when the keys update. This
    # is useful for monolithic shunts designed to be updated frequently,
    # detrimental to intrinsic because it overwrites computed vectors.
    BIND "shunt-attractor" 0
}
